### ISSUE TITLE
Missing column name

### ISSUE THREAD

**Issue by YovaKem** [rloganiv/claimrank-allennlp#2]
For the preprocessing code to be compatible with the data as published [here](https://stonybrooknlp.github.io/PoMo/), I had to change 

```
PM_FIELDS = ['input', 'name', 'target', 'sentence', 'id', 'previous_sentence',
             'next_sentence', 'file']
```

to 

```
PM_FIELDS = ['input', 'name', 'target', 'sentence', 'id', 'previous_sentence',
             'next_sentence', 'score', 'file']
```

Thus adding a column name for the second to last column which was otherwise processed as the filename.

**Comment by rloganiv** [comment]
Hi @YovaKem,

Thanks for pointing this out. Update incoming.

Best,

@rloganiv
